# Generated by Django 5.0.1 on 2024-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
